PYTHON-3355 Test with consistent versions of crypt_shared and server
mongodb/mongo-python-driver pull request #1033
Opened 2022-08-09 20:48 UTC by juliusgeo

2022-08-09 21:08 UTC, ShaneHarvey requested changes

2022-08-09 21:08 UTC, ShaneHarvey commented on .evergreen/config.yml
> +          - ".rapid"
We still want to test rapid versions.

2022-08-09 21:08 UTC, ShaneHarvey commented on .evergreen/run-tests.sh
> +      REAL_VERSION="$(mongod --version | head -n1 | cut -d v -f3 | cut -d - -f1 -f2)"
remove `cut -d - -f1 -f2` since we need to keep the -rcX piece.

2022-08-09 21:08 UTC, ShaneHarvey commented on .evergreen/run-tests.sh
> +      export PATH=../crypt_shared/bin:$PATH
Indent 4 spaces instead of 2.

2022-08-09 21:42 UTC, ShaneHarvey commented on .evergreen/run-tests.sh
> +      REAL_VERSION="$(mongod --version | head -n1 | cut -d v -f3 | cut -d - -f1 -f2)"
Removing it has the same behavior:
```
$ mongod --version | head -n1 | cut -d v -f3 
6.0.0-rc4
```
Let's remove it

2022-08-09 21:49 UTC, ShaneHarvey commented on .evergreen/config.yml
> +          - ".rapid"
Oh interesting, what if we update rapid to r6.1.0-alpha? To do that you create a PR like this: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/217

2022-08-11 14:15 UTC, blink1073 commented
[Error](https://evergreen.mongodb.com/task_log_raw/mongo_python_driver_test_macos_encryption__platform~macos_1100_auth~auth_ssl~nossl_encryption~encryption_crypt_shared_test_6.0_sharded_cluster_patch_3204290e93594f8ffe537ca5e7ed071d4c13056e_62f5093861837d540618fa0e_22_08_11_13_50_49/0?type=T#L1748) looks relevant: `pymongocrypt.errors.MongoCryptError: csfle lib_create() failed: Cannot initialize the Mongo Crypt Shared Support Library`

2022-08-11 20:50 UTC, ShaneHarvey commented
Full error:
```
 [2022/08/11 14:04:59.786] ERROR: test_legacy_fle2_validatorAndPartialFieldExpression_create_with_a_validator_on_an_encrypted_field_is_an_error (test.test_encryption.TestSpec)
 [2022/08/11 14:04:59.786] ----------------------------------------------------------------------
 [2022/08/11 14:04:59.786] Traceback (most recent call last):
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/test/__init__.py", line 596, in wrap
 [2022/08/11 14:04:59.786]     return f(*args, **kwargs)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/test/__init__.py", line 596, in wrap
 [2022/08/11 14:04:59.786]     return f(*args, **kwargs)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/test/test_encryption.py", line 664, in run_scenario
 [2022/08/11 14:04:59.786]     self.run_scenario(scenario_def, test)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/test/utils_spec_runner.py", line 520, in run_scenario
 [2022/08/11 14:04:59.786]     client = rs_client(
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/test/utils.py", line 576, in rs_client
 [2022/08/11 14:04:59.786]     return _mongo_client(h, p, **kwargs)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/test/utils.py", line 556, in _mongo_client
 [2022/08/11 14:04:59.786]     return MongoClient(uri, port, **client_options)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/pymongo/mongo_client.py", line 848, in __init__
 [2022/08/11 14:04:59.786]     self._encrypter = _Encrypter(self, self.__options.auto_encryption_opts)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/pymongo/encryption.py", line 336, in __init__
 [2022/08/11 14:04:59.786]     self._auto_encrypter = AutoEncrypter(
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/venv-encryption/lib/python3.9/site-packages/pymongocrypt/auto_encrypter.py", line 31, in __init__
 [2022/08/11 14:04:59.786]     self.mongocrypt = MongoCrypt(mongo_crypt_opts, callback)
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/venv-encryption/lib/python3.9/site-packages/pymongocrypt/mongocrypt.py", line 179, in __init__
 [2022/08/11 14:04:59.786]     self.__init()
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/venv-encryption/lib/python3.9/site-packages/pymongocrypt/mongocrypt.py", line 243, in __init
 [2022/08/11 14:04:59.786]     self.__raise_from_status()
 [2022/08/11 14:04:59.786]   File "/System/Volumes/Data/data/mci/8f5831c6762ad7c1185896252cbde96b/src/venv-encryption/lib/python3.9/site-packages/pymongocrypt/mongocrypt.py", line 259, in __raise_from_status
 [2022/08/11 14:04:59.786]     raise exc
 [2022/08/11 14:04:59.786] pymongocrypt.errors.MongoCryptError: csfle lib_create() failed: Cannot initialize the Mongo Crypt Shared Support Library when it is already initialized. [Error 3, code 1]
```

Strange, can you reproduce this error locally with 6.0.0 crypt_shared and 6.0.0 sharded cluster?

2022-08-16 00:52 UTC, ShaneHarvey approved these changes

2022-08-16 04:18 UTC, merged