PYTHON-3232 Improved change stream event visibility for C2C Replication
mongodb/mongo-python-driver pull request #1062
Opened 2022-09-26 22:08 UTC by juliusgeo

2022-09-26 22:28 UTC, blink1073 requested changes

2022-09-26 22:28 UTC, blink1073 commented on pymongo/collection.py
> +        show_expanded_events: Optional[bool] = None,
Needs docs and versionadded.  Looks like we missed `full_document_before_change` in the docstring earlier as well.

2022-09-26 22:28 UTC, blink1073 commented on pymongo/database.py
> +        show_expanded_events: Optional[bool] = None,
Same comment as collection method

2022-09-26 22:28 UTC, blink1073 commented on pymongo/mongo_client.py
> +        show_expanded_events: Optional[bool] = None,
Here as well

2022-09-26 22:53 UTC, ShaneHarvey requested changes

2022-09-26 22:53 UTC, ShaneHarvey commented on pymongo/aggregation.py
> +        show_expanded_events=None,
Since you're implementing PYTHON-3232 in this PR can you rename the title and close PYTHON-3373 as a duplicate of PYTHON-3232?

2022-09-27 20:44 UTC, blink1073 commented
Can you merge from master to pick up https://github.com/mongodb/mongo-python-driver/pull/1063?

2022-09-27 20:48 UTC, ShaneHarvey requested changes
Let's add a changelog entry for show_expanded_events too.

2022-09-27 21:22 UTC, ShaneHarvey commented on pymongo/change_stream.py
> +        if self._show_expanded_events is True:
Yeah that's the point. `if x` works with anything truthy while `if x is True` doesn't. It's more verbose and less flexible.

2022-09-27 21:23 UTC, ShaneHarvey commented on pymongo/change_stream.py
> +        if self._show_expanded_events is True:
See
```
Don’t compare boolean values to True or False using ==:
# Correct:
if greeting:
# Wrong:
if greeting == True:
Worse:

# Wrong:
if greeting is True:
```
https://peps.python.org/pep-0008/

2022-09-27 21:57 UTC, blink1073 approved these changes
LGTM!

2022-09-27 22:00 UTC, ShaneHarvey approved these changes

2022-09-27 22:31 UTC, merged