PYTHON-3388 Propagate Original Error for Write Errors Labeled NoWritesPerformed
mongodb/mongo-python-driver pull request #1117
Opened 2022-11-14 23:22 UTC by juliusgeo

2022-11-15 23:51 UTC, blink1073 commented on test/test_retryable_writes.py
> +    def succeeded(self, event: CommandSucceededEvent):
Needs a return type per mypy error

2022-11-15 23:51 UTC, blink1073 commented on test/test_retryable_writes.py
> +    ):  # TODO: Make this a real integration test where we stepdown the primary.
Was this TODO meant to be here?  It looks like it was referring to the TestRetryableWritesTxnNumber class.

2022-11-15 23:51 UTC, blink1073 commented on test/test_retryable_writes.py
> +        assert exc.exception.code == 91
Should use `self.assertEquals`

2022-11-16 15:53 UTC, blink1073 submitted a review, later dismissed
LGTM!

2022-11-16 20:27 UTC, ShaneHarvey requested changes

2022-11-16 20:27 UTC, ShaneHarvey commented on pymongo/mongo_client.py
> +        self._indefinite_error: Optional[WriteConcernError] = None
We can't use an instance variable to track this because it makes MongoClient not thread safe.

2022-11-16 20:27 UTC, ShaneHarvey commented on pymongo/mongo_client.py
> +                    self._indefinite_error = exc
_indefinite_error  is not needed. `last_error` already tracks the error that should be propagated.

2022-11-16 23:17 UTC, blink1073 commented
Mypy failure:

```python
pymongo/mongo_client.py:1416: error: Incompatible types in assignment
(expression has type "PyMongoError", variable has type
"Optional[WriteConcernError]")  [assignment]
                            self._indefinite_error = exc
```

2022-11-16 23:53 UTC, ShaneHarvey commented on pymongo/mongo_client.py
> +                    self._indefinite_error = exc
Why do you think we need to track the last WriteConcernError? This change should not track WriteConcernErrors any differently than other errors. This change is about errors labeled with NoWritesPerformed which may or may not be a WriteConcernError.

2022-11-16 23:54 UTC, ShaneHarvey commented on pymongo/mongo_client.py
> +                with self._indefinite_error_lock:
Adding a lock here does not help at all. It's still not thread safe.

2022-11-17 20:44 UTC, blink1073 commented on pymongo/mongo_client.py
> +                        assert last_error is not None
I assume this is here for the type checker.  I think we should be more conservative and check `if exc.has_error_label("NoWritesPerformed") and last_error is not None`

2022-11-17 20:50 UTC, ShaneHarvey requested changes

2022-11-17 20:50 UTC, ShaneHarvey commented on pymongo/mongo_client.py
> +                        raise
There's a missing condition here. If the current error is NoWritesPerformed and the last error is None, then we must raise the current error even though it's labelled NoWritesPerformed. This is True for all the cases above with `assert last_error is not None` too.

2022-11-18 17:17 UTC, blink1073 approved these changes

2022-11-21 22:50 UTC, ShaneHarvey requested changes
Can you add the test from https://github.com/mongodb/specifications/pull/1349?

2022-11-28 17:28 UTC, blink1073 commented
The pre-commit failure was addressed in #1122

2022-11-29 23:04 UTC, ShaneHarvey approved these changes

2022-12-02 01:54 UTC, merged