Support overflow integers in fallback_encoder.
mongodb/mongo-python-driver pull request #1243
Opened 2023-06-16 19:36 UTC by stephan-hof

Hi,

I'm regularly dealing with 64-bit *unsigned* integers.
Those range from `[0, (2**64) - 1]`. So they are outside of the 64-bit *signed* integers from  [BSONs](https://bsonspec.org/spec.html) `"\x12" e_name int64 64-bit integer`.

Up to now pymongo rejects those immediately with an OverflowError so the application must deal with them.
For us this is pretty cumbersome, since we have a pretty complex structure and finding those large numbers would mean to 'traverse' through the whole document before giving it to pymongo.

Performance and code wise this is not very ideal so my thinking was:
To convert the document to BSON, pymongo must traverse the document anyway.
So lets handle this 'big integer' like any other unknown type and call the `fallback_encoder` (if given). 
Then let the fallback_encoder deal with it. This is now up to me, like it is already with unknown types.

In other words: If pymongo/bson detects an integer outside its supported range the `fallback_encoder` gets called.
If no `fallback_encoder` is given or if `fallback_encoder` gives back a 'big integer' again the usual `OverflowError` is thrown.

2023-06-21 13:31 UTC, blink1073 requested changes

2023-06-21 16:59 UTC, stephan-hof commented on bson/__init__.py
> +    except IntegerOverflow:
Many thanks for giving this pull-requestion attention. Your suggestion makes sense to me and already pushed a commit to address it. + merged latest master into the branch as well.

How do you handle the 'resolve conversation' ? Should I press it or is this something the reviewer does after accepting the change ?

2023-06-21 19:59 UTC, blink1073 commented on bson/__init__.py
> +    except IntegerOverflow:
The reviewer does it.  Done!

2023-06-21 20:04 UTC, blink1073 approved these changes
LGTM, thank you!

2023-06-22 18:25 UTC, ShaneHarvey requested changes
Feel free to add yourself to `doc/contributors.rst` if you like!

2023-06-22 18:25 UTC, ShaneHarvey commented on bson/__init__.py
> +        if error.args != ("BSON can only handle up to 8-byte ints",):
Could you replace this with `if not isinstance(value, int):`? This way the fallback encoder won't be called multiple times for one OverflowError in this case:
```
>>> bson.encode({'a' {'b': 'c': 2<<65}}, codec_options=CodecOptions(...fallback_encoder=lambda val: val)))

```

2023-06-26 19:19 UTC, ShaneHarvey approved these changes
Thanks @stephan-hof, LGTM!

2023-06-26 19:19 UTC, ShaneHarvey commented on test/test_custom_types.py
> +    def test_call_only_once_for_not_handled_big_integers(self):
Nice test!

2023-06-26 19:20 UTC, merged

2023-06-27 06:12 UTC, stephan-hof commented
Just wanted to say: Many thanks for taking this serious and giving me a great contribution experience.