PYTHON-3807 add types to mongo_client.py
mongodb/mongo-python-driver pull request #1315
Opened 2023-07-18 21:28 UTC by sleepyStick

https://jira.mongodb.org/browse/PYTHON-3807

2023-07-25 21:11 UTC, ShaneHarvey requested changes

2023-07-25 21:11 UTC, ShaneHarvey commented on pymongo/collection.py
> +    ) -> CommandCursor[_DocumentType]:
I believe list_indexes always returns MutableMapping. Could you confirm?

_DocumentType is intended to represent documents in the collection, not index documents, so let's avoid using it here.

2023-07-25 21:11 UTC, ShaneHarvey commented on pymongo/collection.py
> +            Mapping[str, Any],
This cast shouldn't be needed. Is the return type of `_update` inaccurate?

2023-07-25 21:11 UTC, ShaneHarvey commented on pymongo/collection.py
> +            CommandCursor[MutableMapping[str, Any]],
We don't need this cast after we fix list_indexes.

2023-08-01 17:34 UTC, ShaneHarvey approved these changes

2023-08-01 17:34 UTC, ShaneHarvey commented on bson/codec_options.py
> +
Should this be removed?

2023-08-01 18:55 UTC, sleepyStick commented on bson/codec_options.py
> +
yes! thanks for catching that!

2023-08-01 22:06 UTC, ShaneHarvey approved these changes

2023-08-01 23:49 UTC, merged