PYTHON-3801 gRPC POC phase 1
mongodb/mongo-python-driver pull request #1317
Opened 2023-07-24 17:17 UTC by NoahStapp

gRPC POC phase 1 work

2023-07-24 21:34 UTC, ShaneHarvey requested changes
Could you flesh this out a bit more by adding a `MongoClient(grpc=True)` flag which then configures the Pool setting? That way we can use this branch to compare TCP vs gRPC performance?

2023-07-25 18:15 UTC, NoahStapp commented
> Could you flesh this out a bit more by adding a `MongoClient(grpc=True)` flag which then configures the Pool setting? That way we can use this branch to compare TCP vs gRPC performance?

Done! I added a minimal working example in tests/grpc_example.py that depends on the grpc-enabled serverless proxy running locally.

2023-07-25 20:34 UTC, ShaneHarvey commented
Looks like grpcio still does not support pypy: https://github.com/grpc/grpc/issues/4221

2023-07-26 19:01 UTC, NoahStapp commented
> Looks like grpcio still does not support pypy: [grpc/grpc#4221](https://github.com/grpc/grpc/issues/4221) That's a bit disappointing. Perhaps we could work on that in the future?
> 
> Edit: looks like the pypy error might be fixed by installing cython 0.29.36: [grpc/grpc#29517 (comment)](https://github.com/grpc/grpc/issues/29517#issuecomment-1631282367)

This fix didn't work for me, even putting cython 0.29.36 in our pyproject.toml `[build-system]` `requires` section. We'll have to investigate further in a future POC phase.

2023-07-26 20:59 UTC, ShaneHarvey commented on pymongo/aggregation.py
> -    from pymongo.pool import SocketInfo
Could you open a new ticket to do this SocketInfo->Connection renaming as it's own PR? It makes this POC difficult to review.

2023-07-26 21:01 UTC, merged

2023-07-26 21:38 UTC, ShaneHarvey commented
LGTM!