PYTHON-3879 Rename SocketInfo to Connection
mongodb/mongo-python-driver pull request #1329
Opened 2023-07-26 22:39 UTC by NoahStapp

2023-07-26 23:22 UTC, ShaneHarvey commented on pymongo/pyopenssl_context.py
> +        """Wrap an existing Python socket connector and return a TLS socket
Looks like the renaming went a little too far.

2023-07-26 23:22 UTC, ShaneHarvey commented on pymongo/pool.py
> +    def get_conn(self, handler=None):
Since where changing this anyway, how do you feel about calling this "pool.checkout()" to closer to the CMAP spec?

2023-07-26 23:22 UTC, ShaneHarvey commented on pymongo/pool.py
> +    def return_conn(self, conn):
Same here but called "checkin"

2023-07-26 23:22 UTC, ShaneHarvey commented on pymongo/aggregation.py
> +        connection: Connection,
What do you think about naming this "conn: Connection" to be more succinct everywhere?

2023-07-27 21:31 UTC, blink1073 commented
There's still a lot of docstrings that have unnecessary changes.

2023-07-27 21:31 UTC, blink1073 commented on pymongo/collection.py
> +            exclusive :class:`~socket.socket` conn to MongoDB. If the
These three docstring changes should be reverted

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +        Unix domain conns are also supported. The socket path must be percent
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +            client = MongoClient('/tmp/mongodb-27017.conn')
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +            free conns. Defaults to ``None`` (no timeout).
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +            establishing a conn.
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +            certificates passed from the other end of the conn.
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +            # Use conn.command directly to avoid implicitly creating
Should be Connection.command

2023-07-27 21:31 UTC, blink1073 commented on pymongo/mongo_client.py
> +        def _cmd(session, server, connection, read_preference):
Should be `conn`

2023-07-27 21:31 UTC, blink1073 commented on pymongo/monitor.py
> +        # Clear our pooled conn.
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/monitoring.py
> +        Emitted when the driver starts attempting to check out a Connection.
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/monitoring.py
> +        Emitted when the driver's attempt to check out a Connection fails.
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/monitoring.py
> +    a new conn.
Revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/monitoring.py
> +    """Published when the driver starts attempting to check out a conn.
revert (all the docstring changes in this file).

2023-07-27 21:31 UTC, blink1073 commented on pymongo/network.py
> +    # Only Monitor conns can be cancelled.
revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/network.py
> +# Errors raised by conns (and TLS conns) when in non-blocking mode.
revert

2023-07-27 21:31 UTC, blink1073 commented on pymongo/network.py
> +            raise OSError("conn closed")
revert

2023-07-27 22:26 UTC, ShaneHarvey requested changes

2023-07-27 22:26 UTC, ShaneHarvey commented on pymongo/command_cursor.py
> +        self.__conn_mgr: Any = None
Unfortunately motor uses this property so I think it needs to stay for now: https://github.com/mongodb/motor/blob/2c0570f701c7bfb04e3b158aff7f0136ac75b61c/motor/core.py#L1695

2023-07-27 23:36 UTC, NoahStapp commented
Sorry for all the docstring issues, I figured out how to have PyCharm filter for that correctly. They should all be resolved now.

2023-07-28 00:49 UTC, blink1073 approved these changes
LGTM!

2023-07-28 17:04 UTC, merged

2024-08-01 09:58 UTC, msm416 commented
Hi, should this change not be mentioned in the [Changelog](https://pymongo.readthedocs.io/en/stable/changelog.html)? Thanks!

2024-08-01 17:24 UTC, ShaneHarvey commented
> Hi, shouldn't this change be mentioned in the [Changelog](https://pymongo.readthedocs.io/en/stable/changelog.html)? Thanks!

We did not mention it because SocketInfo/Connection are private internal apis. Are you depending it for something?

2024-08-02 09:04 UTC, msm416 commented
@ShaneHarvey - I see, it's alright since I've changed the import to workaround for now but will probably re-write my logic to not make use of those classes.

SocketInfo was documented in pymongo v3: https://pymongo.readthedocs.io/en/3.12.3/api/pymongo/pool.html

To me, `private api == what's not documented`, but I expected that if something is once documented but then removed from docs, that should appear in some changelogs for visibility.

2024-08-02 18:27 UTC, ShaneHarvey commented
Yes we removed that documentation in 4.0 but even in v3, those classes were still intended to be private. An app couldn't actually access a MongoClient's Pool or Connection classes so there was no reason to document those apis. I'd still be curious to hear what you're using those classes for.

2024-08-03 10:26 UTC, msm416 commented
> [..] those classes were still intended to be private

I see.

> I'd still be curious to hear what you're using those classes for.

I'm using the class in a test: to patch Connection.send_message with a custom method wrapper that counts the calls for this method, to give a just a brief description.

2024-08-05 18:13 UTC, ShaneHarvey commented
Interesting, could your test use a CommandListener instead https://pymongo.readthedocs.io/en/stable/api/pymongo/monitoring.html?

2024-08-07 12:32 UTC, msm416 commented
Thank you @ShaneHarvey ! Yes, I made it work with a Listener in the end, after following your docs (`CommandLogger`) 👍