PYTHON-4038: Explicitly check for OperationFailure exception type in retryable reads
mongodb/mongo-python-driver pull request #1425
Opened 2023-11-08 19:53 UTC by Jibola

2023-11-08 19:59 UTC, Jibola commented
I need to add a test case into PyMongo to ensure this doesn't recur

2023-11-13 18:34 UTC, NoahStapp approved these changes

2023-11-13 18:57 UTC, ShaneHarvey requested changes
Still needs a mockupdb test where the server returns a missing or 0 error code. 

Also could you update the PR title and changelog to describe the bug that's being fixed?

2023-11-15 19:13 UTC, ShaneHarvey approved these changes

2023-11-15 19:17 UTC, NoahStapp approved these changes

2023-11-15 20:03 UTC, merged