PYTHON-4111 Search index management operations fail with a different error message
mongodb/mongo-python-driver pull request #1462
Opened 2023-12-20 17:37 UTC by blink1073

2023-12-20 17:43 UTC, NoahStapp requested changes
One minor comment, otherwise LGTM!

2023-12-20 17:43 UTC, NoahStapp commented on .evergreen/resync-specs.sh
> +    # printf "\nIgnored files for ${PWD}:\n"
Remove this block of comments?

2023-12-20 23:00 UTC, blink1073 commented on .evergreen/resync-specs.sh
> +    # printf "\nIgnored files for ${PWD}:\n"
Fixed

2024-01-02 15:00 UTC, NoahStapp approved these changes

2024-01-04 11:32 UTC, merged