PYTHON-4183: Unavoidable breaking change with BSON
mongodb/mongo-python-driver pull request #1498
Opened 2024-02-01 18:50 UTC by Jibola

2024-02-01 22:51 UTC, blink1073 approved these changes
LGTM!

2024-02-01 23:28 UTC, ShaneHarvey requested changes

2024-02-01 23:28 UTC, ShaneHarvey commented on doc/changelog.rst
> +    >>> client = MongoClient()
Could you remove all the duplicated imports in this example?

2024-02-02 18:28 UTC, ShaneHarvey approved these changes

2024-02-05 13:49 UTC, Jibola commented on doc/changelog.rst
> +
```suggestion

```

2024-02-05 13:50 UTC, Jibola commented on doc/changelog.rst
> +    SON([('driver', SON([('name', 'PyMongo'), ('version', '4.7.0.dev0')])), ('os', SON([('type', 'Darwin'), ('name', 'Darwin'), ('architecture', 'arm64'), ('version', '14.3')])), ('platform', 'CPytho
```suggestion
    SON([('driver', SON([('name', 'PyMongo'), ('version', '4.7.0.dev0')])), ('os', SON([('type', 'Darwin'), ('name', 'Darwin'), ('architecture', 'arm64'), ('version', '14.3')])), ('platform', 'CPython 3.11.6.final.0')])

```

2024-02-05 16:24 UTC, Jibola commented
Failures are unrelated to my change. Filed a ticket against them here: https://jira.mongodb.org/browse/PYTHON-4193

2024-02-05 17:49 UTC, merged