PYTHON-4117 Require 4.3.1+ server version when using failCommand errorLabels option
mongodb/mongo-python-driver pull request #1526
Opened 2024-02-16 12:02 UTC by blink1073

Also fixes PYTHON-4018

2024-02-16 20:38 UTC, ShaneHarvey approved these changes

2024-02-16 20:40 UTC, ShaneHarvey requested changes
One test is failing:
```

 [2024/02/16 04:18:28.646] =================================== FAILURES ===================================
 [2024/02/16 04:18:28.646] _ TestCommandMonitoringWriteConcernError.test_A_retryable_write_with_write_concern_errors_publishes_success_event _
 [2024/02/16 04:18:28.646] self = <test.test_command_monitoring.TestCommandMonitoringWriteConcernError testMethod=test_A_retryable_write_with_write_concern_errors_publishes_success_event>
 [2024/02/16 04:18:28.646]     def test_case(self):
 [2024/02/16 04:18:28.646] >       self.run_scenario(spec)
 [2024/02/16 04:18:28.646] test/unified_format.py:1851:
 [2024/02/16 04:18:28.646] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 [2024/02/16 04:18:28.646] test/unified_format.py:1798: in run_scenario
 [2024/02/16 04:18:28.646]     self._run_scenario(spec, uri)
 [2024/02/16 04:18:28.646] test/unified_format.py:1834: in _run_scenario
 [2024/02/16 04:18:28.646]     self.check_events(expect_events)
 [2024/02/16 04:18:28.646] test/unified_format.py:1712: in check_events
 [2024/02/16 04:18:28.646]     self.match_evaluator.match_event(event_type, expected_event, actual_events[idx])
 [2024/02/16 04:18:28.646] test/unified_format.py:872: in match_event
 [2024/02/16 04:18:28.646]     self.match_result(reply, actual.reply)
 [2024/02/16 04:18:28.646] test/unified_format.py:791: in match_result
 [2024/02/16 04:18:28.646]     return self._match_document(expectation, actual, is_root=not in_recursive_call)
 [2024/02/16 04:18:28.646] test/unified_format.py:780: in _match_document
 [2024/02/16 04:18:28.646]     self.match_result(value, actual[key], in_recursive_call=True)
 [2024/02/16 04:18:28.646] test/unified_format.py:791: in match_result
 [2024/02/16 04:18:28.646]     return self._match_document(expectation, actual, is_root=not in_recursive_call)
 [2024/02/16 04:18:28.646] test/unified_format.py:787: in _match_document
 [2024/02/16 04:18:28.646]     self.test.assertEqual(expected_keys, set(actual.keys()))
 [2024/02/16 04:18:28.646] E   AssertionError: Items in the second set but not the first:
 [2024/02/16 04:18:28.646] E   'errorLabels'
 [2024/02/16 04:18:28.646] ------------------------------ Captured log call -------------------------------
 [2024/02/16 04:18:28.646] INFO     pymongo.serverSelection:logger.py:94 {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f65496abac0>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 65cf50f6de68da9dcd97141c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=WriteConcernError(\"None, full error: {'code': 91, 'errorLabels': ['RetryableWriteError']}\")>, <ServerDescription ('localhost', 27018) server_type: RSSecondary, rtt: 0.0005081769999719654>, <ServerDescription ('localhost', 27019) server_type: RSArbiter, rtt: 0.001811891000045307>]>", "clientId": {"$oid": "65cf50f6de68da9dcd97141c"}, "remainingTimeMS": 29}
```

2024-02-17 02:56 UTC, blink1073 commented
Test failures are CSOT and https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-4182.

2024-02-20 18:11 UTC, ShaneHarvey requested changes

2024-02-20 18:11 UTC, ShaneHarvey commented on pymongo/helpers.py
> +            wce = wce.copy()
Does this work with if result is a RawBSONDocument? Can we add a test for it?

2024-02-20 18:15 UTC, ShaneHarvey approved these changes

2024-02-20 19:28 UTC, merged