PYTHON-3601 OIDC: Add Documentation Examples
mongodb/mongo-python-driver pull request #1601
Opened 2024-04-17 03:12 UTC by blink1073

2024-04-17 15:38 UTC, NoahStapp approved these changes
Minor nitpicks, otherwise looks great!

2024-04-17 15:38 UTC, NoahStapp commented on doc/examples/authentication.rst
> +The driver supports OIDC for  workload identity, defined as an identity you assign to a software workload
```suggestion
The driver supports OIDC for workload identity, defined as an identity you assign to a software workload
```

2024-04-17 15:38 UTC, NoahStapp commented on doc/examples/authentication.rst
> +    props = dict(ENVIRONMENT="azure", TOKEN_RESOURCE="<audience>")
```suggestion
    props = {"ENVIRONMENT": "azure", "TOKEN_RESOURCE": "<audience>"}
```

Nitpicky, but we should probably steer away from using `dict` in examples for readability/performance reasons.

2024-04-17 15:38 UTC, NoahStapp commented on doc/examples/authentication.rst
> +    props = dict(ENVIRONMENT="gcp", TOKEN_RESOURCE="<audience>")
```suggestion
    props = {"ENVIRONMENT": "gcp", "TOKEN_RESOURCE": "<audience>")
```

2024-04-17 15:38 UTC, NoahStapp commented on doc/examples/authentication.rst
> +    props = dict(OIDC_CALLBACK=MyCallback())
```suggestion
    props = {"OIDC_CALLBACK": MyCallback()}
```

2024-04-17 15:38 UTC, NoahStapp commented on doc/examples/authentication.rst
> +  props = dict(OIDC_CALLBACK=MyCallback())
```suggestion
  props = {"OIDC_CALLBACK": MyCallback()}
```

2024-04-17 15:38 UTC, NoahStapp commented on doc/examples/authentication.rst
> +    props = dict(OIDC_CALLBACK=MyCallback())
```suggestion
  props = {"OIDC_CALLBACK": MyCallback()}
```

2024-04-17 15:38 UTC, NoahStapp requested changes
Minor nitpicks, otherwise looks great!

2024-04-19 18:12 UTC, blink1073 commented
ping @NoahStapp for final review.  :)

2024-04-19 18:15 UTC, NoahStapp approved these changes

2024-04-19 18:29 UTC, merged