PYTHON-4483 Use hatch as task runner
mongodb/mongo-python-driver pull request #1728
Opened 2024-07-09 19:53 UTC by blink1073

2024-07-10 22:51 UTC, NoahStapp commented
Unrelated EG test failure? https://spruce.mongodb.com/task/mongo_python_driver_tests_windows_python_version__platform~windows_64_vsMulti_small_auth_ssl~auth_ssl_python_version_windows~3.9_test_rapid_replica_set_patch_5cba4c44fe9ec633232f08bf8c6086252a3e5573_668db265bb8f750007f12779_24_07_09_21_57_58?execution=1&sortBy=STATUS&sortDir=ASC

2024-07-10 22:56 UTC, NoahStapp requested changes
Way more concise than tox, awesome! Just a few minor typos.

2024-07-10 22:56 UTC, NoahStapp commented on .evergreen/run-tests.sh
> +    # Setup encryption necessary.
```suggestion
    # Setup encryption if necessary.
```

2024-07-10 22:56 UTC, NoahStapp commented on .evergreen/teardown-encyrption.sh
Typo in name, should be `teardown-encryption.sh`

2024-07-10 22:56 UTC, NoahStapp commented on hatch.toml
> +test-async = "test test/asynchronous/ {args}"
Hatch lets you reference previously-defined commands? Nice.

2024-07-11 12:19 UTC, blink1073 commented on .evergreen/teardown-encyrption.sh
Fixed!

2024-07-11 16:52 UTC, ShaneHarvey approved these changes

2024-07-11 16:56 UTC, merged