PYTHON-4571 - Add async examples to PyMongo's tutorial
mongodb/mongo-python-driver pull request #1744
Opened 2024-07-23 20:34 UTC by NoahStapp

We can't run `doctest` on the async tutorial because `doctest` doesn't support running async code in the Python REPL.

2024-07-30 19:53 UTC, blink1073 requested changes

2024-07-30 19:53 UTC, blink1073 commented on doc/async-tutorial.rst
> +.. todo:: link to table of Python <-> BSON types
Copied from other tutorial?

2024-07-30 19:53 UTC, blink1073 commented on doc/async-tutorial.rst
> +  def get(post_id):
This should be async

2024-07-30 20:19 UTC, NoahStapp commented on doc/async-tutorial.rst
> +.. todo:: link to table of Python <-> BSON types
Good catch, removed.

2024-08-01 18:10 UTC, blink1073 approved these changes
LGTM!

2024-08-01 18:10 UTC, merged