PYTHON-4707 Migrate test_bulk.py to async
mongodb/mongo-python-driver pull request #1827
Opened 2024-09-03 17:19 UTC by sleepyStick

2024-09-03 20:31 UTC, NoahStapp requested changes

2024-09-03 20:31 UTC, NoahStapp commented on test/test_bulk.py
> +        self.secondary.admin.command("configureFailPoint", "rsApplyStop", mode="alwaysOn")
This needs to be `rsSyncApplyStop`.

2024-09-04 17:12 UTC, sleepyStick commented on test/test_bulk.py
> +        self.secondary.admin.command("configureFailPoint", "rsApplyStop", mode="alwaysOn")
thanks for catching that! fixed!

2024-09-04 17:28 UTC, NoahStapp approved these changes

2024-09-04 17:36 UTC, merged