PYTHON-4695 Fix test event loop policy and improve error traceback for ClientBulkWriteException
mongodb/mongo-python-driver pull request #1828
Opened 2024-09-04 13:08 UTC by blink1073

2024-09-04 18:30 UTC, ShaneHarvey requested changes
Great improvements but we still need to fix the bug where ClientBulkWriteException contains a raw TimeoutError. That should never be possible even if the event loop policy is incompatible. We should be catching TimeoutError and raising pymongo's NetworkTimeout.

2024-09-05 20:09 UTC, ShaneHarvey submitted a review, later dismissed

2024-09-06 01:11 UTC, blink1073 commented
> Great improvements but we still need to fix the bug where ClientBulkWriteException contains a raw TimeoutError. That should never be possible even if the event loop policy is incompatible. We should be catching TimeoutError and raising pymongo's NetworkTimeout.

I opened [PYTHON-4740](https://jira.mongodb.org/browse/PYTHON-4740) to track that question separately.

2024-09-06 17:05 UTC, ShaneHarvey approved these changes

2024-09-06 17:17 UTC, merged