PYTHON-4733 Migrate test_auth.py to async
mongodb/mongo-python-driver pull request #1838
Opened 2024-09-05 21:07 UTC by sleepyStick

2024-09-06 16:11 UTC, sleepyStick commented
so...i'm honestly not sure what I did to this commit history HAHA I was just trying to rebase my branch..

2024-09-06 19:11 UTC, NoahStapp commented
Can you undo the rebase and just merge master into the un-rebased branch? There's changes already in master that show up in this PR.

2024-09-06 22:22 UTC, sleepyStick commented
I think I did it correctly?

2024-09-06 22:37 UTC, ShaneHarvey commented on test/test_auth.py
> +            def _run_async():
Any threading test needs to be skipped for async because async client doesn't support multithreading.

2024-09-09 12:13 UTC, NoahStapp requested changes

2024-09-09 12:13 UTC, NoahStapp commented on test/test_auth.py
> +        if not _IS_SYNC:
Use `@async_client_context.require_sync` as a decorator for sync-only tests instead.

2024-09-09 12:13 UTC, NoahStapp commented on test/test_auth.py
> +        if _IS_SYNC:
Since the async client doesn't support multithreading, we don't need to have `AutoAuthenticateThread` support async.

2024-09-09 17:16 UTC, NoahStapp approved these changes
Great work!

2024-09-09 18:35 UTC, merged