PYTHON-4753 [Build Failure] Async tests missing awaits
mongodb/mongo-python-driver pull request #1851
Opened 2024-09-10 22:04 UTC by sleepyStick

2024-09-10 22:11 UTC, blink1073 commented
Docs failure is unrelated, I'm asking the docs team about it

2024-09-10 22:11 UTC, sleepyStick commented
> Docs failure is unrelated, I'm asking the docs team about it

cool cool, tysm!

2024-09-11 15:36 UTC, ShaneHarvey requested changes

2024-09-11 15:36 UTC, ShaneHarvey commented on test/asynchronous/test_auth.py
> -        set_name = await client.admin.command(HelloCompat.LEGACY_CMD).get("setName")
We can probably replace these setName lines with `client_context.replica_set_name`.

2024-09-12 15:57 UTC, ShaneHarvey approved these changes

2024-09-12 15:59 UTC, merged