PYTHON-4737 Migrate test_binary.py to async
mongodb/mongo-python-driver pull request #1863
Opened 2024-09-17 21:29 UTC by sleepyStick

More like test_binary shouldn't have any client stuff in it....I've moved tests that require the client from `test_binary.py` to `test_client.py`

2024-09-17 23:20 UTC, ShaneHarvey requested changes

2024-09-17 23:20 UTC, ShaneHarvey commented on test/asynchronous/test_client.py
> +        from_java = (
Any way we can share this blob with test_binary? Same for from_csharp.

2024-09-20 00:46 UTC, ShaneHarvey requested changes

2024-09-20 00:46 UTC, ShaneHarvey commented on test/asynchronous/test_client.py
> +from bson.binary import *
We try to avoid * imports for a few reasons: https://stackoverflow.com/questions/2386714/why-is-import-bad

2024-09-20 00:46 UTC, ShaneHarvey commented on test/asynchronous/test_client.py
> +from test.test_binary import TestBinary
Importing TestBinary directly will actually cause pytest/unittest to pick up and run TestBinary in this file too. Instead we need to mangle to name, like: `from test.test_binary import TestBinary as BinaryBase` or move the test data out of TestBinary into to a global var that we can import.

2024-09-20 00:46 UTC, ShaneHarvey commented on test/asynchronous/test_client.py
> +    @async_client_context.require_connection
I beleive we can remove the `require_connection`s now that this is in test_client.

2024-09-24 15:54 UTC, sleepyStick commented
My brain forgot to check up on this until now haha, but thanks for the feedback! I think I made the appropriate changes :)

2024-09-24 19:14 UTC, ShaneHarvey requested changes
<img width="1328" alt="Screenshot 2024-09-24 at 12 13 11 PM" src="https://github.com/user-attachments/assets/8ccf26f6-4d94-4432-b0da-be5476627f01">
Hmm, my TestBinary as BinaryBase idea doesn't work. We'll have to do something else.

2024-09-24 19:34 UTC, sleepyStick commented
Ah good catch! I'll try something else!

2024-09-25 18:10 UTC, ShaneHarvey approved these changes
LGTM!

2024-09-30 18:17 UTC, merged