Migrate test_retryable_reads.py to async
mongodb/mongo-python-driver pull request #1877
Opened 2024-09-27 00:14 UTC by sleepyStick

Note: I made `test_pool_paused_error_is_retryable` require sync because it uses threads, but not sure if I should be changing the test to not use threads instead?

2024-09-27 16:57 UTC, NoahStapp requested changes

2024-09-27 16:57 UTC, NoahStapp commented on test/asynchronous/test_retryable_reads.py
> +        self.addAsyncCleanup(client.close)
We don't need to add explicit cleanup when using the helper methods to create clients, they do the cleanup for us.

2024-09-27 16:57 UTC, NoahStapp commented on test/asynchronous/test_retryable_reads.py
> +            self.addAsyncCleanup(client.close)
Same here.

2024-09-30 22:38 UTC, sleepyStick commented on test/asynchronous/test_retryable_reads.py
> +_TEST_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "retryable_reads", "legacy")
good catch! I fixed it (I think), but uh why is `_TEST_PATH` not used anywhere in the file? (like as far as I can tell, its just defined but never used??)

2024-10-01 14:44 UTC, NoahStapp commented on test/asynchronous/test_retryable_reads.py
> +_TEST_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "retryable_reads", "legacy")
Good point! I actually think our retryable read tests are fully converted to unified, so we can remove `_TEST_PATH` here entirely.

2024-10-01 15:38 UTC, sleepyStick commented on test/asynchronous/test_retryable_reads.py
> +_TEST_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "retryable_reads", "legacy")
removed it :)

2024-10-01 16:03 UTC, NoahStapp approved these changes

2024-10-01 16:16 UTC, merged