PYTHON-4815 Migrate test_discovery_and_monitoring.py to async
mongodb/mongo-python-driver pull request #1893
Opened 2024-10-02 23:14 UTC by sleepyStick

2024-10-03 17:29 UTC, NoahStapp requested changes

2024-10-03 17:29 UTC, NoahStapp commented on pymongo/asynchronous/monitor.py
> +                await self._topology.receive_cluster_time(details.get("$clusterTime"))
Nice catch!

2024-10-03 17:29 UTC, NoahStapp commented on test/asynchronous/test_discovery_and_monitoring.py
> +SDAM_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "discovery_and_monitoring")
This needs to be updated to point to `test/discovery_and_monitoring` instead of `test/asynchronous/discovery_and_monitoring`.

2024-10-03 17:29 UTC, NoahStapp commented on test/asynchronous/test_discovery_and_monitoring.py
> +        topology.handle_error(
Missing an `await` here.

2024-10-03 17:29 UTC, NoahStapp commented on test/asynchronous/test_discovery_and_monitoring.py
> +                    got_hello(c, common.partition_node(response[0]), response[1])
Missing an `await` here.

2025-02-12 03:36 UTC, blink1073 commented
@sleepyStick should this be closed in favor of #2093?

2025-02-12 19:34 UTC, sleepyStick commented
> @sleepyStick should this be closed in favor of #2093?

yeah, I was gonna close it once #2093 was merged haha

2025-03-17 23:39 UTC, closed without merging