PYTHON-4579 Stop gossiping $clusterTime on SDAM connections
mongodb/mongo-python-driver pull request #1925
Opened 2024-10-14 17:50 UTC by ShaneHarvey

[Draft] PYTHON-4579 Stop gossiping $clusterTime on SDAM connections

2025-02-25 19:39 UTC, ShaneHarvey commented on pymongo/asynchronous/monitor.py
> +        except asyncio.CancelledError:
Ah this was a merge conflict artifact. I'll remove.

2025-02-25 23:02 UTC, ShaneHarvey commented on pymongo/asynchronous/topology.py
> +        # TODO: Verify that app errors update the $clusterTime.
Tracked in https://jira.mongodb.org/browse/DRIVERS-3118. I'll remove this TODO.

2025-02-25 23:04 UTC, ShaneHarvey commented
Ready for another look.

2025-02-26 14:52 UTC, NoahStapp requested changes

2025-02-26 14:52 UTC, NoahStapp commented on pymongo/asynchronous/monitor.py
> +                None,
Can we remove `cluster_time` as a parameter to `_hello` entirely now?

2025-02-26 21:03 UTC, ShaneHarvey commented on pymongo/asynchronous/monitor.py
> +                None,
Good call, done.

2025-02-26 21:13 UTC, NoahStapp approved these changes
LGTM!

2025-02-26 21:18 UTC, merged