PYTHON-2727 Start testing against MongoDB 5.0 in Evergreen
mongodb/mongo-python-driver pull request #631
Opened 2021-05-28 00:15 UTC by prashantmital

2021-05-28 17:07 UTC, prashantmital commented
Some action items from the failures:

- [ ] Move OCSP testing to Ubuntu 18
- [ ] Move snappy/zlib/zstd compression tests to Ubuntu 18
- [ ] Move PyOpenSSL tests to Ubuntu 18
- [ ] Investigate the remaining test failures

2021-06-05 00:14 UTC, ShaneHarvey commented
There are a lot of failures here, is this ready for review?

2021-06-05 00:59 UTC, prashantmital commented
@ShaneHarvey failures are transient. I think this can be reviewed now. There might 1-2 more failures to deal with which can happen during/after review.

2021-06-07 19:08 UTC, ShaneHarvey requested changes

2021-06-07 19:08 UTC, ShaneHarvey commented on .evergreen/config.yml
> +    # Test standalone and sharded only on 4.4 and later.
Let's remove 4.4 and make this only 5.0.

2021-06-07 19:08 UTC, ShaneHarvey commented on .evergreen/config.yml
> +    - '.5.0'
Let's remove 4.4 and make this only 5.0.

2021-06-07 19:12 UTC, merged