PYTHON-3075 - [Backport-4.0] Fix server selection when topology type is Unknown
mongodb/mongo-python-driver pull request #841
Opened 2022-02-02 19:58 UTC by blink1073

2022-02-02 20:20 UTC, ShaneHarvey commented
evergreen patch

2022-02-02 20:24 UTC, ShaneHarvey commented
evergreen patch

2022-02-02 23:21 UTC, ShaneHarvey requested changes

2022-02-02 23:21 UTC, ShaneHarvey commented on pymongo/message.py
> +from bson import codec_options
Unneeded.

2022-02-02 23:22 UTC, ShaneHarvey commented
(updated the title because Backport-4 was being interpreted as a link to a jira ticket).

2022-02-02 23:27 UTC, blink1073 commented on pymongo/message.py
> +from bson import codec_options
Fixed

2022-02-03 12:44 UTC, blink1073 commented
Encryption run [passed](https://spruce.mongodb.com/task/mongo_python_driver_4.0_tests_python_version_amazon1_test_encryption__platform~awslinux_auth_ssl~noauth_nossl_python_version~3.8_encryption~encryption_test_4.4_sharded_cluster_patch_93334cac4359c23fe75c3cb2062d104944718435_61fb13512fbabe23afff190b_22_02_02_23_27_14/tests?execution=0&sortBy=STATUS&sortDir=ASC).

2022-02-03 18:37 UTC, ShaneHarvey approved these changes

2022-02-03 20:21 UTC, merged