PYTHON-3110 Remove use of example.com in CSFLE tests (#848)
mongodb/mongo-python-driver pull request #851
Opened 2022-02-08 18:53 UTC by blink1073

(cherry picked from commit 561ee7cf77fcbdefb9e2f46691f2b2ba4c65198b)

2022-02-08 18:56 UTC, blink1073 commented
Scheduled encryption runs for Python 2.7 and 3.9

2022-02-08 19:01 UTC, ShaneHarvey requested changes

2022-02-08 19:01 UTC, ShaneHarvey commented on test/test_encryption.py
> +        with self.assertRaisesRegex(EncryptionError, self.invalid_host_error):
invalid_host_error hasn't been defined

2022-02-08 19:46 UTC, blink1073 commented on test/test_encryption.py
> +        with self.assertRaisesRegex(EncryptionError, self.invalid_host_error):
Fixed

2022-02-08 19:47 UTC, blink1073 commented on test/test_encryption.py
> +        with self.assertRaisesRegex(EncryptionError, self.invalid_host_error):
And rescheduled encryption tasks

2022-02-09 22:00 UTC, blink1073 commented
Same issue with Encryption Python 3.8 Amazon Linux 2018 (Enterprise) NoAuth NoSSL, trying with a Windows variant.

2022-02-09 23:44 UTC, blink1073 commented
Ah, I was misreading the logs.  I fixed the missing `re` import and re-triggered Encryption runs for 2.7 and 3.9

2022-02-10 00:20 UTC, juliusgeo approved these changes
LGTM!

2022-02-10 12:29 UTC, merged