PYTHON-2850 [v3.13] Deprecate mapReduce command
mongodb/mongo-python-driver pull request #861
Opened 2022-02-10 18:00 UTC by juliusgeo

Deprecate mapReduce helpers

2022-02-10 23:25 UTC, behackett requested changes

2022-02-10 23:25 UTC, behackett commented on pymongo/collection.py
> +           Deprecated :meth:`map_reduce`. Support for this function is deprecated in
We should also say that this is removed in PyMongo 4.0:
https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#collection-map-reduce-and-collection-inline-map-reduce-are-removed

You should say here what users should do instead. An abbreviated version of what the PyMongo 4 upgrade guide says.

2022-02-10 23:25 UTC, behackett commented on pymongo/collection.py
> +           Deprecated :meth:`inline_map_reduce`. Support for this function is deprecated in
Same comment here.

2022-02-11 00:08 UTC, juliusgeo commented
Managed to accidentally merge with master rather than the v3.13 branch so there are a tonnn of messed up changes. I think I'm just gonna create this from scratch in a new PR given how small it is.

2022-02-11 16:45 UTC, blink1073 approved these changes
LGTM, thanks!

2022-02-11 16:50 UTC, merged