PYTHON-3093 Change streams support for user-facing PIT pre- and post-images
mongodb/mongo-python-driver pull request #972
Opened 2022-06-14 17:14 UTC by bcwarner

2022-06-14 19:19 UTC, blink1073 requested changes

2022-06-14 19:19 UTC, blink1073 commented on test/change_streams/unified/change-streams-errors.json
> +          "minServerVersion": "4.2",
We're pinning this to 4.4 pending https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-3292

2022-06-14 19:19 UTC, blink1073 commented on pymongo/mongo_client.py
> +            full_document_before_change,
Needs an update to docstring for parameters and versionchanged

2022-06-14 19:19 UTC, blink1073 commented on pymongo/database.py
> +            full_document_before_change,
Needs an update to docstring for parameters and versionchanged

2022-06-15 00:18 UTC, bcwarner commented
Skips tests that weren't relevant.

2022-06-15 18:21 UTC, juliusgeo approved these changes
LGTM!

2022-06-15 18:22 UTC, merged

2022-06-15 19:09 UTC, ShaneHarvey commented on pymongo/database.py
> +            to the ``$changeStream`` stage. Allowed values: 'updateLookup', 'whenAvailable', 'required'.
Does this line need to be applied to Database and MongoClient as well?